# Generated by Django 4.0.3 on 2022-08-17 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0005_answer_vote_question_voter_alter_answer_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='vote',
            new_name='voter',
        ),
    ]
